/**
 * Realistic seed data for the Learning Path Graph.
 * Split from seed.js so the dataset can grow independently of the loader.
 */

export const seedTopics = [
  // ---- Web Development ----
  { id_topic: 'wd-html', name: 'HTML & Semantic Markup', category: 'Web Development', level: 'beginner', estHours: 20, summary: 'The structural skeleton of every web page.', goals: ['Build accessible, semantic HTML documents', 'Structure a multi-section page'] },
  { id_topic: 'wd-css', name: 'CSS & Responsive Design', category: 'Web Development', level: 'beginner', estHours: 30, summary: 'Styling, layout and responsive behaviour with modern CSS.', goals: ['Style pages with flexbox and grid', 'Build mobile-first responsive layouts'] },
  { id_topic: 'wd-js', name: 'JavaScript Fundamentals', category: 'Web Development', level: 'beginner', estHours: 60, summary: 'The programming language of the web: values, control flow, functions and events.', goals: ['Write functions and handle events', 'Manipulate the DOM'] },
  { id_topic: 'wd-git', name: 'Git & Version Control', category: 'Web Development', level: 'beginner', estHours: 15, summary: 'Track changes, branch, merge and collaborate with Git.', goals: ['Commit, branch and merge', 'Resolve conflicts'] },
  { id_topic: 'wd-dom', name: 'DOM & Browser APIs', category: 'Web Development', level: 'intermediate', estHours: 20, summary: 'How the browser renders pages and the APIs available to JavaScript.', goals: ['Query and update the DOM', 'Work with fetch and storage APIs'] },
  { id_topic: 'wd-typescript', name: 'TypeScript', category: 'Web Development', level: 'intermediate', estHours: 30, summary: 'Typed JavaScript that scales to large codebases.', goals: ['Model data with types and interfaces', 'Use generics'] },
  { id_topic: 'wd-react', name: 'React & Component Design', category: 'Web Development', level: 'intermediate', estHours: 60, summary: 'Building interactive UIs with components, state and effects.', goals: ['Compose components and manage state', 'Fetch data with effects'] },
  { id_topic: 'wd-nodejs', name: 'Node.js & Express', category: 'Web Development', level: 'intermediate', estHours: 50, summary: 'JavaScript on the server: HTTP servers, routing and middleware.', goals: ['Build REST endpoints with Express', 'Read environment config'] },
  { id_topic: 'wd-sql', name: 'Relational Databases & SQL', category: 'Web Development', level: 'intermediate', estHours: 30, summary: 'Model data relationally and query it with SQL.', goals: ['Write SELECT, JOIN and aggregate queries', 'Design a small schema'] },
  { id_topic: 'wd-rest', name: 'REST API Design', category: 'Web Development', level: 'intermediate', estHours: 25, summary: 'Designing clean, versioned HTTP APIs that clients love.', goals: ['Design resources and status codes', 'Document an API'] },
  { id_topic: 'wd-testing', name: 'Frontend Testing', category: 'Web Development', level: 'intermediate', estHours: 30, summary: 'Unit and integration testing for UI code.', goals: ['Write unit tests with a runner', 'Test component behaviour'] },
  { id_topic: 'wd-nextjs', name: 'Next.js & Full-Stack Frameworks', category: 'Web Development', level: 'advanced', estHours: 40, summary: 'Full-stack React frameworks with routing, rendering and data fetching.', goals: ['Use file-based routing and SSR', 'Deploy a full-stack app'] },
  { id_topic: 'wd-graphql', name: 'GraphQL & API Modernisation', category: 'Web Development', level: 'advanced', estHours: 35, summary: 'Query languages and typed schemas as an alternative to REST.', goals: ['Design a typed schema', 'Resolve nested queries'] },
  { id_topic: 'wd-perf', name: 'Web Performance & Core Web Vitals', category: 'Web Development', level: 'advanced', estHours: 25, summary: 'Measuring and optimising load speed and interactivity.', goals: ['Profile with Lighthouse', 'Optimise bundles and rendering'] },

  // ---- Data Science & ML ----
  { id_topic: 'ds-python', name: 'Python for Data Science', category: 'Data Science & ML', level: 'beginner', estHours: 40, summary: 'Python fundamentals with a focus on data workflows.', goals: ['Write Python scripts and modules', 'Use Jupyter notebooks'] },
  { id_topic: 'ds-numpy', name: 'NumPy & Vectorised Computing', category: 'Data Science & ML', level: 'intermediate', estHours: 25, summary: 'Fast numerical computing with multidimensional arrays.', goals: ['Vectorise arithmetic over arrays', 'Use broadcasting'] },
  { id_topic: 'ds-pandas', name: 'Pandas & Data Wrangling', category: 'Data Science & ML', level: 'intermediate', estHours: 35, summary: 'Cleaning, reshaping and analysing tabular data.', goals: ['Load and clean messy datasets', 'Group and aggregate data'] },
  { id_topic: 'ds-viz', name: 'Data Visualisation', category: 'Data Science & ML', level: 'intermediate', estHours: 20, summary: 'Telling stories with charts using Matplotlib and Seaborn.', goals: ['Create exploratory charts', 'Design publication-quality figures'] },
  { id_topic: 'ds-stats', name: 'Statistics & Probability', category: 'Data Science & ML', level: 'intermediate', estHours: 50, summary: 'The statistical foundations behind data science.', goals: ['Describe distributions and uncertainty', 'Run hypothesis tests'] },
  { id_topic: 'ds-linalg', name: 'Linear Algebra for ML', category: 'Data Science & ML', level: 'intermediate', estHours: 40, summary: 'Vectors, matrices and eigen-decompositions under the hood of ML.', goals: ['Operate on vectors and matrices', 'Understand matrix factorisation'] },
  { id_topic: 'ds-ml', name: 'Machine Learning Fundamentals', category: 'Data Science & ML', level: 'advanced', estHours: 70, summary: 'Training and interpreting classic ML models.', goals: ['Train supervised models', 'Prevent overfitting'] },
  { id_topic: 'ds-fe', name: 'Feature Engineering', category: 'Data Science & ML', level: 'advanced', estHours: 25, summary: 'Turning raw data into signal that models can learn from.', goals: ['Build feature pipelines', 'Handle categorical and missing data'] },
  { id_topic: 'ds-eval', name: 'Model Evaluation & Validation', category: 'Data Science & ML', level: 'advanced', estHours: 25, summary: 'Honest metrics, cross-validation and model selection.', goals: ['Choose the right metric', 'Use cross-validation'] },
  { id_topic: 'ds-dl', name: 'Deep Learning', category: 'Data Science & ML', level: 'advanced', estHours: 80, summary: 'Neural networks, backpropagation and training at scale.', goals: ['Build neural nets from scratch', 'Train with optimisers'] },
  { id_topic: 'ds-nlp', name: 'Natural Language Processing', category: 'Data Science & ML', level: 'advanced', estHours: 60, summary: 'Making sense of text with modern NLP.', goals: ['Tokenise and embed text', 'Fine-tune a transformer'] },
  { id_topic: 'ds-cv', name: 'Computer Vision', category: 'Data Science & ML', level: 'advanced', estHours: 60, summary: 'Teaching machines to see with convolutional networks.', goals: ['Build CNNs', 'Use transfer learning'] },
  { id_topic: 'ds-mlops', name: 'MLOps & Model Deployment', category: 'Data Science & ML', level: 'advanced', estHours: 45, summary: 'Shipping models: pipelines, monitoring and CI/CD.', goals: ['Package and serve models', 'Automate retraining'] },

  // ---- Backend Engineering ----
  { id_topic: 'be-networks', name: 'Computer Networks Fundamentals', category: 'Backend Engineering', level: 'intermediate', estHours: 30, summary: 'HTTP, TCP/IP and how data moves across the internet.', goals: ['Explain TCP/IP and DNS', 'Debug with curl and net tools'] },
  { id_topic: 'be-databases', name: 'Database Design & Modeling', category: 'Backend Engineering', level: 'intermediate', estHours: 40, summary: 'Relational modelling, normalisation and indexing.', goals: ['Normalise a schema', 'Plan indexes'] },
  { id_topic: 'be-system', name: 'System Design Fundamentals', category: 'Backend Engineering', level: 'advanced', estHours: 50, summary: 'Designing scalable services: load balancing, storage and APIs.', goals: ['Sketch scalable architectures', 'Reason about trade-offs'] },
  { id_topic: 'be-docker', name: 'Containers & Docker', category: 'Backend Engineering', level: 'intermediate', estHours: 30, summary: 'Packaging and running applications reproducibly.', goals: ['Containerise a service', 'Orchestrate with compose'] },
  { id_topic: 'be-k8s', name: 'Kubernetes Orchestration', category: 'Backend Engineering', level: 'advanced', estHours: 40, summary: 'Running containerised workloads at scale.', goals: ['Deploy workloads to a cluster', 'Use config and secrets'] },
  { id_topic: 'be-mq', name: 'Message Queues & Event-Driven Systems', category: 'Backend Engineering', level: 'advanced', estHours: 35, summary: 'Decoupling services with queues and event streaming.', goals: ['Publish and consume events', 'Handle retries and idempotency'] },
  { id_topic: 'be-cloud', name: 'Cloud Computing & AWS', category: 'Backend Engineering', level: 'advanced', estHours: 40, summary: 'Compute, storage and networking on the major clouds.', goals: ['Provision cloud resources', 'Secure and monitor them'] },
  { id_topic: 'be-caching', name: 'Caching & CDNs', category: 'Backend Engineering', level: 'intermediate', estHours: 20, summary: 'Making systems fast with caches, CDNs and lazy loading.', goals: ['Design a cache strategy', 'Invalidate effectively'] },
  { id_topic: 'be-sec', name: 'API Security & Auth', category: 'Backend Engineering', level: 'intermediate', estHours: 25, summary: 'Authentication, authorisation and securing APIs.', goals: ['Implement OAuth/OIDC flows', 'Harden endpoints'] },
  { id_topic: 'be-microservices', name: 'Microservices Architecture', category: 'Backend Engineering', level: 'advanced', estHours: 45, summary: 'Splitting systems into independently deployable services.', goals: ['Decompose a monolith', 'Handle inter-service concerns'] },
];

/** REQUIRES edges: [source, target] means "source requires target". */
export const REQUIRES = [
  // Web development
  ['wd-css', 'wd-html'],
  ['wd-dom', 'wd-js'],
  ['wd-typescript', 'wd-js'],
  ['wd-react', 'wd-js'],
  ['wd-react', 'wd-dom'],
  ['wd-react', 'wd-html'],
  ['wd-react', 'wd-css'],
  ['wd-nodejs', 'wd-js'],
  ['wd-nodejs', 'wd-git'],
  ['wd-rest', 'wd-nodejs'],
  ['wd-rest', 'wd-sql'],
  ['wd-nextjs', 'wd-react'],
  ['wd-nextjs', 'wd-nodejs'],
  ['wd-testing', 'wd-react'],
  ['wd-testing', 'wd-js'],
  ['wd-graphql', 'wd-rest'],
  ['wd-graphql', 'wd-nodejs'],
  ['wd-perf', 'wd-css'],
  ['wd-perf', 'wd-react'],
  ['wd-perf', 'wd-nodejs'],
  // Data science
  ['ds-python', 'wd-git'],
  ['ds-numpy', 'ds-python'],
  ['ds-pandas', 'ds-python'],
  ['ds-pandas', 'ds-numpy'],
  ['ds-viz', 'ds-pandas'],
  ['ds-stats', 'ds-python'],
  ['ds-linalg', 'ds-python'],
  ['ds-ml', 'ds-python'],
  ['ds-ml', 'ds-stats'],
  ['ds-ml', 'ds-linalg'],
  ['ds-ml', 'ds-numpy'],
  ['ds-fe', 'ds-ml'],
  ['ds-fe', 'ds-pandas'],
  ['ds-eval', 'ds-ml'],
  ['ds-eval', 'ds-stats'],
  ['ds-dl', 'ds-ml'],
  ['ds-dl', 'ds-numpy'],
  ['ds-dl', 'ds-linalg'],
  ['ds-nlp', 'ds-dl'],
  ['ds-nlp', 'ds-stats'],
  ['ds-cv', 'ds-dl'],
  ['ds-cv', 'ds-linalg'],
  ['ds-mlops', 'ds-ml'],
  ['ds-mlops', 'wd-nodejs'],
  // Backend
  ['be-databases', 'wd-sql'],
  ['be-system', 'be-networks'],
  ['be-system', 'be-databases'],
  ['be-system', 'wd-sql'],
  ['be-docker', 'wd-nodejs'],
  ['be-docker', 'wd-git'],
  ['be-k8s', 'be-docker'],
  ['be-k8s', 'be-networks'],
  ['be-mq', 'wd-nodejs'],
  ['be-mq', 'be-networks'],
  ['be-cloud', 'be-networks'],
  ['be-cloud', 'be-docker'],
  ['be-cloud', 'wd-sql'],
  ['be-caching', 'be-networks'],
  ['be-caching', 'wd-nodejs'],
  ['be-sec', 'wd-nodejs'],
  ['be-sec', 'be-networks'],
  ['be-microservices', 'be-system'],
  ['be-microservices', 'be-docker'],
  ['be-microservices', 'be-mq'],
];

export const seedPaths = [
  {
    id_path: 'path-webdev',
    name: 'Web Developer',
    tagline: 'From your first HTML tag to production React.',
    description: 'The classic journey from static pages to interactive, full-stack web applications.',
    icon: 'code',
    topics: [
      'wd-html', 'wd-css', 'wd-js', 'wd-git', 'wd-dom', 'wd-typescript',
      'wd-react', 'wd-sql', 'wd-nodejs', 'wd-rest', 'wd-testing',
      'wd-nextjs', 'wd-graphql', 'wd-perf',
    ],
  },
  {
    id_path: 'path-data',
    name: 'Data Scientist',
    tagline: 'Turn raw data into models that predict the future.',
    description: 'From Python and statistics to deep learning, NLP and computer vision.',
    icon: 'chart-line',
    topics: [
      'ds-python', 'wd-git', 'ds-numpy', 'ds-pandas', 'ds-stats', 'ds-linalg',
      'ds-viz', 'ds-ml', 'ds-fe', 'ds-eval', 'ds-dl', 'ds-nlp', 'ds-cv', 'ds-mlops',
    ],
  },
  {
    id_path: 'path-backend',
    name: 'Backend Engineer',
    tagline: 'Build the systems that power the internet.',
    description: 'Networks, databases, services and the architecture decisions that hold them together.',
    icon: 'server',
    topics: [
      'be-networks', 'wd-git', 'wd-sql', 'wd-nodejs', 'be-databases', 'be-system',
      'be-docker', 'be-mq', 'be-sec', 'be-caching', 'be-microservices', 'be-k8s', 'be-cloud',
    ],
  },
];

export const seedSkills = [
  { id_skill: 'skill-programming', name: 'Programming Fundamentals', description: 'Core coding literacy in a mainstream language.', taughtBy: ['wd-js', 'ds-python', 'wd-typescript'] },
  { id_skill: 'skill-web-foundations', name: 'HTML & CSS', description: 'Markup and styling for the web.', taughtBy: ['wd-html', 'wd-css'] },
  { id_skill: 'skill-version-control', name: 'Version Control', description: 'Collaborating on code with Git.', taughtBy: ['wd-git'] },
  { id_skill: 'skill-frontend', name: 'Frontend Engineering', description: 'Building interactive user interfaces.', taughtBy: ['wd-dom', 'wd-react', 'wd-testing', 'wd-nextjs'] },
  { id_skill: 'skill-backend', name: 'Backend Engineering', description: 'Server-side APIs and services.', taughtBy: ['wd-nodejs', 'wd-rest', 'wd-graphql', 'be-sec'] },
  { id_skill: 'skill-data-stores', name: 'Data Stores & SQL', description: 'Designing and querying databases.', taughtBy: ['wd-sql', 'be-databases'] },
  { id_skill: 'skill-data-analysis', name: 'Data Analysis', description: 'Wrangling and visualising data.', taughtBy: ['ds-pandas', 'ds-viz', 'ds-numpy'] },
  { id_skill: 'skill-statistics', name: 'Statistics & Probability', description: 'Quantifying uncertainty.', taughtBy: ['ds-stats'] },
  { id_skill: 'skill-linear-algebra', name: 'Linear Algebra', description: 'Maths for high-dimensional data.', taughtBy: ['ds-linalg'] },
  { id_skill: 'skill-machine-learning', name: 'Machine Learning', description: 'Training models from data.', taughtBy: ['ds-ml', 'ds-fe', 'ds-eval'] },
  { id_skill: 'skill-deep-learning', name: 'Deep Learning', description: 'Neural networks and their applications.', taughtBy: ['ds-dl', 'ds-nlp', 'ds-cv'] },
  { id_skill: 'skill-mlops', name: 'MLOps & Deployment', description: 'Shipping ML to production.', taughtBy: ['ds-mlops'] },
  { id_skill: 'skill-networking', name: 'Networking', description: 'How systems talk to each other.', taughtBy: ['be-networks'] },
  { id_skill: 'skill-system-design', name: 'System Design', description: 'Designing scalable architectures.', taughtBy: ['be-system'] },
  { id_skill: 'skill-containers', name: 'Containers & Orchestration', description: 'Running workloads reproducibly.', taughtBy: ['be-docker', 'be-k8s'] },
  { id_skill: 'skill-distributed-systems', name: 'Distributed Systems', description: 'Queues, events and service decoupling.', taughtBy: ['be-mq', 'be-microservices'] },
  { id_skill: 'skill-cloud', name: 'Cloud & Infrastructure', description: 'Provisioning and managing cloud resources.', taughtBy: ['be-cloud'] },
  { id_skill: 'skill-performance', name: 'Performance Engineering', description: 'Caching and web performance.', taughtBy: ['be-caching', 'wd-perf'] },
];

export const seedUsers = [
  {
    id_user: 'user-amelia',
    name: 'Amelia Chen',
    email: 'amelia@example.com',
    password: 'password123',
    avatarColor: '#8b5cf6',
    focus: 'Frontend engineering',
    enrolledPathId: 'path-webdev',
    completed: ['wd-html', 'wd-css', 'wd-js'],
  },
  {
    id_user: 'user-bima',
    name: 'Bima Putra',
    email: 'bima@example.com',
    password: 'password123',
    avatarColor: '#0ea5e9',
    focus: 'Data science',
    enrolledPathId: 'path-data',
    completed: ['wd-git', 'ds-python', 'ds-numpy'],
  },
  {
    id_user: 'user-ciara',
    name: "Ciara O'Brien",
    email: 'ciara@example.com',
    password: 'password123',
    avatarColor: '#f59e0b',
    focus: 'Backend systems',
    enrolledPathId: 'path-backend',
    completed: ['wd-git', 'wd-sql', 'wd-nodejs', 'be-networks'],
  },
  {
    id_user: 'user-guest',
    name: 'Guest Learner',
    email: 'guest@example.com',
    password: 'password123',
    avatarColor: '#64748b',
    focus: 'Exploring the graph',
    enrolledPathId: null,
    completed: [],
  },
];
